.github/workflows/publish-pypi.yaml
I originally tried to use JRubics/poetry-publish@v1.16 but it seems like if failing with this error:
There is no pypi-token.pypi setting.
Probably a simple action like this can be fine as well
=> avoiding using JRubics/poetry-publish@v1.16

pyproject.toml, rstream/producer.py, tests/test_producer.py, tests/util.py
When specifing different publish_notification callbacks for Send/Send_Batch Just the last one was invoked.
Fixed and added tests to cover this scenario
Bumping poetry version as well to prepare delivering
=> There was a bug in the previous software version.

docs/examples/super_stream_producer.py, rstream/__init__.py, rstream/superstream.py, rstream/superstream_consumer.py, rstream/superstream_producer.py, tests/conftest.py, tests/test_consumer.py, tests/test_producer.py, tests/util.py
Implementing the consumer side of super-stream with the tests
This PR implements consumer side logic for super-stream (https://github.com/qweeze/rstream/issues/58)
We are not implementing an auto-reconnect logic, and single-active-consumer functionality will be implemented on a different PR.
=> Implementing consumer side of superstream 

README.md, docs/examples/manual_server_offset_tracking/consumer.py, docs/examples/super_stream/super_stream_consumer.py, rstream/__init__.py, rstream/consumer.py, tests/test_consumer.py, tests/util.py
This PR allows a user to manage server-side offsets storing and tracking:
https://blog.rabbitmq.com/posts/2021/09/rabbitmq-streams-offset-tracking/
It exposes store_offset and query_offset to the consumer callback through the consumer object so that an user can store the offset after consuming messages (for example every 1000 messages consumed).
It also adds tests.
=> manual offset implementation

docs/examples/producers_with_confirmations/send_batch_with_confirmation.py, docs/examples/producers_with_confirmations/send_with_confirmation.py, pyproject.toml, rstream/producer.py
This closes https://github.com/qweeze/rstream/issues/90
There was a bug in the _send_batch as just the last batch was set to confirm ignoring all the others.
=> fixing publish confirmation for send_batch

README.md
Apparently the load balancer section in README was duplicate
=> removing duplicate section in readme

docs/examples/check_connection_broken/consumer_handle_connections_issues.py, docs/examples/check_connection_broken/producer_handle_connections_issues.py, docs/examples/producers_with_confirmations/send_batch_with_confirmation.py, docs/examples/producers_with_confirmations/send_with_confirmation.py, rstream/client.py, rstream/producer.py, tests/util.py
It is better to consider all confirmation handlers as asynchronous tasks.
Some few tests around performance are needed
=> treat all handle callbacks as asyncio tasks

rstream/client.py
=> fix(client): Fix cleanup of Client._waiters dict

rstream/client.py, rstream/consumer.py, tests/conftest.py, tests/test_consumer.py
This closes: https://github.com/qweeze/rstream/issues/126 
This closes: https://github.com/qweeze/rstream/issues/123
This PR is running the delivery callback of the consumer in a different thread in order to let the listener unblocked to receive new frame.
It allows the defined consumer callback to be able to do synchronous requests like in the unit test
=> Improve callback handlers

rstream/client.py, rstream/producer.py
At least when onclosecallback is not set we need to raise an exception to notify the user that a disconnection happened
=> Raise exception when no onclosecallback provided

README.md, docs/examples/basic_consumers/README.md, docs/examples/check_connection_broken/README.md, docs/examples/check_connection_broken/consumer_handle_connections_issues_with_reconnection.py, docs/examples/check_connection_broken/producer_handle_connections_issues_with_reconnect.py, docs/examples/check_connection_broken/superstream_consumer_handle_reconnection.py, docs/examples/check_connection_broken/superstream_producer_handle_reconnection.py, rstream/client.py, rstream/consumer.py, rstream/producer.py, rstream/superstream.py, rstream/superstream_consumer.py, rstream/superstream_producer.py, tests/test_consumer.py, tests/test_producer.py
This closes https://github.com/qweeze/rstream/issues/135  
This closes https://github.com/qweeze/rstream/issues/141 
It should also complete the discussion we had in this issue: https://github.com/qweeze/rstream/issues/121
A new method reconnect_stream is implemented in order to reconnect to a stream in case of disconnection.
This is useful in case of super_stream in case we just loose connection to a partition and we may want simply to reconnect instead of closing the super_stream consumer/producer.
Also locator connections in super_stream are closed when not necessary anymore.
New examples and tests are provided.
=> Reconnect streams

docs/examples/basic_producers/README.md, rstream/producer.py, tests/conftest.py, tests/test_producer.py
This PR improves send_batch performance.
It decouples send_batch from send/send_sub_batch.
In this way we don't need the wrapper list of messages anymore for this case and we safe a loop.
We gain about 15% of performance.
This also reviewed send_wait
This also closes #82
=> improving send_batch

rstream/producer.py
It seems like there was an issue when merging #149 
It seems like the frame optimization implemented wasn't ported for _send_batch but just for send.
This should improve performance of another 10/15% for send_batch.
=> use send_publish_frame in send_batch too

rstream/client.py, rstream/consumer.py, rstream/producer.py, tests/test_consumer.py
This closes #146 
At the moment locator connections are not closed when dedicated.
You can see it when you run the client against a cluster with 3 nodes.
Especially when using superstream this can open more connections than necessary which can create confusion even when we manage disconnections.
With this PR we close and reopen the locator when necessary.
I also made some minor update on name convention on methods.
I made some tests and benchmarks and I don't see any regression
=> avoiding keeping locator connection open when not necessary

docs/examples/reliable_client/BestPracticesClient.py, docs/examples/reliable_client/README.md, docs/examples/super_stream/README.md, docs/examples/super_stream/super_stream_consumer.py, docs/examples/super_stream/super_stream_producer.py, docs/examples/super_stream/super_stream_producer_key.py, rstream/__init__.py, rstream/client.py, rstream/constants.py, rstream/consumer.py, rstream/producer.py, rstream/schema.py, rstream/superstream.py, rstream/superstream_consumer.py, rstream/superstream_producer.py, tests/conftest.py, tests/http_requests.py, tests/test_client.py, tests/test_consumer.py, tests/test_producer.py
This closes #156 
The SuperstreamProducer is now taking in input a new field: super_stream_creation_option of type
```
class SuperStreamCreationOption:
n_partitions: int
binding_keys: Optional[list[str]] = None
arguments: Optional[dict[str, Any]] = None
```
If the super_stream specified in the super_stream field doesn't exist and super_stream_creation_option is set then it will create the super stream.
Also create_super_stream and delete_super_stream have been implemented in the SuperstreamProducer class
=> adding support for CREATE/DELETE supersteams

docs/examples/reliable_client/BestPracticesClient.py, docs/examples/reliable_client/appsettings.json, pyproject.toml, rstream/client.py, rstream/consumer.py, rstream/producer.py, rstream/superstream_consumer.py, rstream/superstream_producer.py
This closes #182 
This PR is changing the client layer so a few more tests need to be done.
Now the Producer/SuperstreamProducer and Consumer/Superstreamconsumer classes take a new fields: max_publishers_by_connection and max_subscribers_by_connection
In this way you can setup the maximum publishers and subscribers by connections (Before was 256 without possibility to override this value).
Doing some tests with this mode I was also able to discover a bug in client.get_available_id
Also It improves the SuperstreamConsumer connections.
Before the class was creating a new Consumer for every partition of the superstream, while now we are just using a single Consumer and creating different Subscribers.
=> implementing maxProducersByConnection and maxConsumerByConnection

rstream/producer.py
This will avoid an asyncio.CancelledError in _publish_buffered_messages during the close() of the Producer that sometimes happens
=> cancelling background task before publishing remaining items

pyproject.toml
Allow typing_extensions to be included on release version (at the moment it is just in the dev dependencies)
=> adding typing_extensions on non dev dependencies

rstream/client.py
This will close https://github.com/qweeze/rstream/issues/203
At the moment we reset the _last_heartbeat just when we receive an heartbeat response from the server.
This reset should happen everytime we receive a response from server (as per other clients)
=> reset heartbeat timeout when receiving any response from the server

rstream/client.py, tests/test_consumer.py
Hi
After unsubscribe we must clear internal queue because in next subscribe in-memory message can be a problem
=> Fixed a bug when subscriber frames not clears after unsubscribe

rstream/consumer.py, tests/test_consumer.py
Hi
Fixed a bug when used `consumer_update_listener` callback from another subscription in single active consumer mode.
=> Fixed a bug when used `consumer_update_listener` callback from another subscription

rstream/client.py, rstream/consumer.py, rstream/producer.py
```
--- Logging error ---
Traceback (most recent call last):
File "/home/app/.local/lib/python3.12/site-packages/rstream/producer.py", line 236, in _get_or_create_publisher
client = await self._get_or_create_client(stream)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/app/.local/lib/python3.12/site-packages/rstream/producer.py", line 211, in _get_or_create_client
self._clients[stream] = await self._pool.get(
^^^^^^^^^^^^^^^^^^^^^
File "/home/app/.local/lib/python3.12/site-packages/rstream/client.py", line 768, in get
await self.new(
File "/home/app/.local/lib/python3.12/site-packages/rstream/client.py", line 841, in new
await client.start()
File "/home/app/.local/lib/python3.12/site-packages/rstream/client.py", line 236, in start
await self._conn.open()
File …
```
=> Fixed bugs of exception logging

rstream/compression.py, rstream/producer.py
Change type annotation from `list` to `Sequence` in `send_batch` and `send_sub_entry` methods to make variable covariant https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generic-types
=> Change type annotation from `list` to `Sequence`

rstream/consumer.py, tests/test_consumer.py
When the reconnect_stream function runs a subscriber is recreated with the existing subscriber setup. This did not include the original filter configuration leading to the filtering quietly disappearing on reconnect.
Added filter_input to the `_Subscriber` object to track this configuration and passed to the `create_subscriber` during `reconnect_stream`
We have concurrent consumers of a single stream that are using a `topic` application-header to subscribe to certain events. After network errors these consumers lose both client and server-side filter configuration which causes events to be consumed incorrectly.
=> Fix for re-applying subscription filter on reconnect

rstream/_pyamqp/_encode.py, rstream/_pyamqp/constants.py
Adjusted integer encoding in `encode_unknown()` to encode a python int as either an int or long depending on whether the value is within range of AMQP 1.0 standard 32-bit signed integer.
This should address Issue #212 in a way that is more suitable than the solution from PR #214 . While I won't say it's the prettiest thing, at least it preserves proper encoding of int and long types to comply with AMQP 1.0.
=> Fix encoding long values with AMQP 1.0 encoder.

.github/workflows/test.yaml, tests/conftest.py, tests/test_amqp.py, tests/test_consumer.py, tests/test_producer.py
This PR restores the flake8 linting test in the CI workflow and fixes various linting issues that were identified by flake8.
- Uncommented the flake8 test in the GitHub Actions workflow
- Cleaned up unused variables and imports across test files
- Fixed incorrect string encoding in AMQP message bodies
=> Restore flake8 test

.gitignore, Makefile, compose/.gitignore, compose/README.md, compose/ha_tls/Dockerfile, compose/ha_tls/conf/enabled_plugins, compose/ha_tls/conf/rabbitmq.conf, compose/ha_tls/docker-compose.yml, compose/ha_tls/haproxy.cfg, pyproject.toml, rstream/client.py, rstream/consumer.py, rstream/exceptions.py, rstream/producer.py, rstream/utils.py, tests/conftest.py, tests/http_requests.py, tests/test_cluster.py, tests/test_consumer.py, tests/test_producer.py, tests/test_validate_id.py
Refactors the producer implementation to use publisher IDs as map keys instead of reference strings, improving performance and consistency in publisher management.
- Replaces string references with integer IDs as the primary key for tracking publishers
- Updates handler registration to use publisher IDs instead of references
- Modifies publisher creation logic to handle optional references
Breaking changes
- It is not possible to subscribe the same stream twice to the same consumer instance anymore
=> Refactor the producers list replace the reference with the id as map key
