rabbitmq-community/rstream

README.md, rstream/client.py, rstream/connection.py, rstream/consumer.py, rstream/producer.py, tests/conftest.py, tests/test_client.py
=> TLS support

.github/workflows/test.yaml, rstream/exceptions.py, tests/test_consumer.py
=> Fix ci integration

poetry.lock, pyproject.toml
Needed for https://github.com/qweeze/rstream/issues/40
=> bumping uampq library to last version

poetry.lock, pyproject.toml, rstream/__init__.py, rstream/superstream.py, tests/conftest.py, tests/test_producer.py, tests/util.py
Superstream first implementation for Producer.
=> superstream implementation

.github/workflows/test.yaml, README.md, docs/examples/super_stream_consumer.py, docs/examples/super_stream_producer.py, pyproject.toml, rstream/__init__.py, rstream/consumer.py, rstream/superstream_consumer.py, tests/test_amqp.py, tests/test_consumer.py, tests/test_producer.py
The new callback is:
```python
def on_message(msg: AMQPMessage, message_context: MessageContext):
print(
"Received message: {} from stream: {} - message offset: {}".format(msg, message_context.stream,
message_context.offset)
)
```
Fixes https://github.com/qweeze/rstream/issues/62
=> improving consumer subscribe callback returning more info

docs/examples/super_stream/README.md, docs/examples/super_stream/super_stream_consumer.py, docs/examples/super_stream/super_stream_producer.py
Add the example for super stream
=> Add the example for super stream

pyproject.toml, rstream/superstream.py
This is solving: https://github.com/qweeze/rstream/issues/73
=> Improving partitions and routes with cache

README.md, pyproject.toml
Bumping version before releasing
=> bumping version before releasing

README.md, docs/examples/basic_consumers/README.md, docs/examples/basic_consumers/basic_consumer.py, docs/examples/basic_consumers/basic_consumer_offset_next.py, docs/examples/basic_consumers/basic_consumer_offset_offset.py, docs/examples/basic_producers/README.md, docs/examples/basic_producers/producer_send.py, docs/examples/basic_producers/producer_send_batch.py, docs/examples/basic_producers/producer_send_binary.py, docs/examples/basic_producers/producer_send_wait.py, docs/examples/manual_server_offset_tracking/consumer.py, docs/examples/producers_with_confirmations/README.md, docs/examples/producers_with_confirmations/send_batch_with_confirmation.py, docs/examples/producers_with_confirmations/send_with_confirmation.py, docs/examples/single_active_consumer/README.md, pyproject.toml
Adding documentation examples on how to use the client.
=> adding basic producer examples

README.md
Update the documentation focusing to the codec part
=> update documentation [skip ci]

README.md, docs/examples/check_connection_broken/consumer_handle_connections_issues.py, docs/examples/check_connection_broken/producer_handle_connections_issues.py, rstream/client.py, rstream/consumer.py, rstream/producer.py, rstream/superstream_consumer.py, rstream/superstream_producer.py
This PR is adding a callback in Producer/Consumer in order to catch the notification of a connection issue (like if a connection is closed server-side).
Can be a first starting point in order to implements an auto-reconnect mechanism
=> adding an event to catch connections issues

README.md, docs/examples/deduplication/producer_ded.py, docs/examples/super_stream/README.md, docs/examples/super_stream/super_stream_consumer.py, docs/examples/super_stream/super_stream_producer.py, docs/examples/super_stream/super_stream_producer_key.py
Adding examples for super_stream key routing type and deduplication
=> Adding superstream keystrat example

README.md, docs/examples/tls/producer.py
Adding a ssl/tls example, it seems like the old one was deprecated and not working.
=> adding ssl/tls example

README.md
=> add documentation [skip ci]

docs/examples/basic_producers/producer_send.py, rstream/client.py, rstream/connection.py, rstream/encoding.py, rstream/producer.py
This closes https://github.com/qweeze/rstream/issues/133
This PR is implementing the suggestions done in https://github.com/qweeze/rstream/issues/133 in order to improve the performance of Publishing, creating a special case for publishing encode.
=> Frame optimization

rstream/encoding.py
Fixes https://github.com/qweeze/rstream/issues/153
=> Fix overflow error

rstream/client.py, rstream/constants.py, rstream/schema.py, tests/test_client.py
Needed for https://github.com/qweeze/rstream/issues/124 and in general to implement better functionality checks based on server version.
=> Implements ExchangeCommandVersion command

.github/workflows/test.yaml, README.md, docs/examples/filtering/README.md, docs/examples/filtering/consumer_filtering.py, docs/examples/filtering/producer_filtering.py, docs/examples/filtering/super_stream_consumer_filtering.py, docs/examples/filtering/super_stream_producer_filtering.py, pyproject.toml, rstream/__init__.py, rstream/client.py, rstream/connection.py, rstream/constants.py, rstream/consumer.py, rstream/encoding.py, rstream/producer.py, rstream/schema.py, rstream/superstream_consumer.py, rstream/superstream_producer.py, rstream/utils.py, tests/conftest.py, tests/test_client.py, tests/test_consumer.py, tests/test_encoding.py, tests/util.py
This closes #124
This PR implements the new filtering feature available just from RabbitMQ 3.13.
https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#filtering
=> Implement filtering

rstream/client.py
=> check if future is done before set_result in listener

tests/test_consumer.py
This closes #44 
I reworked the test with the new api.
It seems like the issue was just that it was too slow originally to send_batch.
I increased the mark time to 1500 just to be sure the test is stable
=> reactivate timestamp test

pyproject.toml, rstream/producer.py
Bumping version to 0.17.0 and minor clean up
=> preparing release

tests/util.py
This PR should solve some test instability (some tests go to timeout checking if a connection has been deleted)
=> test fixing a timeout in test

pyproject.toml, rstream/client.py, rstream/consumer.py, tests/test_consumer.py
=> add cleanup in unsubscribe
